In [300]:
import numpy as np
#from numpy import*


# 4.1多维数组对象ndarry

In [301]:
data= np.random.randn(2,3)#随机生成一个2行3列的数组
data


array([[-0.10659812, -1.24765292,  0.24945522],
       [ 0.58107332,  2.76384408,  0.39932544]])

In [302]:
data*10            #对数组的一个数学操作

array([[ -1.06598121, -12.47652923,   2.49455215],
       [  5.81073321,  27.6384408 ,   3.99325437]])

In [303]:
data+data

array([[-0.21319624, -2.49530585,  0.49891043],
       [ 1.16214664,  5.52768816,  0.79865087]])

In [304]:
data.shape  #调用shape函数查看数组形状

(2, 3)

In [305]:
data.dtype#调用函数查看数据类型

dtype('float64')

## 4.1.1生成ndarray

In [306]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [307]:
data2=[[1,2,3,4],[4,5,6,7]]
arr2=np.array(data2)        #使用np.array函数组装一个数组
arr2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [308]:
arr2.ndim   #调用ndim输出行数

2

In [309]:
np.zeros((3,3))#调用zeros函数输出一个全零数组

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [310]:
arr3=np.ones((3,3,2))#调用ones函数生成一个3*3*3的全一数组
arr3

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [311]:
np.arange(3)    #arange()生成一个一维数组的函数

array([0, 1, 2])

In [312]:
arr4=np.zeros_like(arr3)
arr4

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [313]:
arr5=np.ones_like(arr3)
arr5

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

## 4.1.2ndarray的数据类型

In [314]:
arr1=np.array([1,2,3,4],dtype=np.float64)#调用array函数组装数组，并规定数组类型
arr1

array([1., 2., 3., 4.])

In [315]:
arr2=np.array([1,2,3,4],dtype=np.int32)
arr2

array([1, 2, 3, 4])

In [316]:
arr1.dtype

dtype('float64')

In [317]:
arr2.dtype

dtype('int32')

In [318]:
arr2.astype(np.float64)  #数组对象调用astype函数实现数据类型转换
#arr2.astype(arr1.dtype)

array([1., 2., 3., 4.])

In [319]:
numeric_strings=np.array(['23','-96.3','5.0'])  
arr4=numeric_strings.astype(np.float64)  #数据类型为字符串的数组
arr4

array([ 23. , -96.3,   5. ])

## 4.1.3数组算术
数组之所以重要是因为它允许你进行批量操作而无需任何for循环

In [320]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [321]:
arr*arr   #矩阵对应元素相乘


array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [322]:
arr-arr
#1/arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [323]:
arr**0.5  # **幂运算符

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [324]:
arr1=np.array([[4,5,6],[4,5,6]],dtype=np.float64)
arr1

array([[4., 5., 6.],
       [4., 5., 6.]])

In [325]:
arr1>arr       #同尺寸矩阵之间可直接进行比较，得到一个bool类型的矩阵

array([[ True,  True,  True],
       [False, False, False]])

## 4.1.4矩阵的索引和切片
数组索引是一个大话题，有很多种方式让你选中数据的子集或者某个单元的元素

In [326]:
arr=np.arange(10)   
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [327]:
arr[5]

5

In [328]:
arr[5:8]   #得到一维数组的一个切片（第5-7个元素）

array([5, 6, 7])

In [329]:
arr[5:8]=11   #对某个切片进行赋值，反映在原数组上
arr

array([ 0,  1,  2,  3,  4, 11, 11, 11,  8,  9])

In [330]:
array_slice=arr[5:8] #这里仅为原数组的视图不是复制 ！！！需要重点理解！！！！  
array_slice[:]=13   #引用一维数组所有元素
array_slice


array([13, 13, 13])

In [331]:
array_copy=array_slice.copy()#利用copy函数实现拷贝，而不是视图
array_copy[1]=56
arr

array([ 0,  1,  2,  3,  4, 13, 13, 13,  8,  9])

In [332]:
array_slice[1]=12   #数组的切片是数组的一个视图
arr

array([ 0,  1,  2,  3,  4, 13, 12, 13,  8,  9])

In [333]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],dtype=np.float64)
arr3d.shape

(2, 2, 3)

In [334]:
arr3d[1,1,1]   #访问数组内某个具体元素

11.0

In [335]:
arr3d[0]   #省略索后续索引值得到降低一个维度的数组
arr3d[0].shape

(2, 3)

In [336]:
arr3d[1,0]  #返回的是一个数组

array([7., 8., 9.])

#### 4.1.4.1数组的切片索引

In [337]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float64)
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [338]:
arr2d[1:,1:2]  #多维数组的切片方式，在每一位维度上与一位数组相同

array([[5.],
       [8.]])

## 4.1.5布尔索引
即根据->数组名[]中[]里面的内容进行判断，然后输出数组内相应的内容

In [339]:
names=np.array(['Bob','Joe','Will','Bob','Will'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will'], dtype='<U4')

In [340]:
data=np.random.randn(5,4)#使用np.random中的randn函数生成一些随机正态分布的数据
data

array([[ 0.66848817, -0.27577373,  0.5004829 ,  0.86306486],
       [-1.05162786, -1.39205408,  1.15392224,  1.18194411],
       [ 0.39137145, -0.88104709,  0.29507996,  1.86380106],
       [-1.71227392, -1.40708455,  0.12678119,  0.00375985],
       [-1.26899426, -0.83884292,  0.55392125, -0.50404272]])

In [341]:
names=='Bob'   #这里生成布尔数组，注意布尔数组的长度要和数据数组的行数一致

array([ True, False, False,  True, False])

In [342]:
data[names!='Bob',2:]  

array([[ 1.15392224,  1.18194411],
       [ 0.29507996,  1.86380106],
       [ 0.55392125, -0.50404272]])

In [343]:
data[(names=='Bob')|(names=='Will')]  

array([[ 0.66848817, -0.27577373,  0.5004829 ,  0.86306486],
       [ 0.39137145, -0.88104709,  0.29507996,  1.86380106],
       [-1.71227392, -1.40708455,  0.12678119,  0.00375985],
       [-1.26899426, -0.83884292,  0.55392125, -0.50404272]])

In [344]:
data[data<0]=0    #利用布尔索引进行赋值
data

array([[0.66848817, 0.        , 0.5004829 , 0.86306486],
       [0.        , 0.        , 1.15392224, 1.18194411],
       [0.39137145, 0.        , 0.29507996, 1.86380106],
       [0.        , 0.        , 0.12678119, 0.00375985],
       [0.        , 0.        , 0.55392125, 0.        ]])

In [345]:
data[names!='Bob']=7
data

array([[6.68488169e-01, 0.00000000e+00, 5.00482900e-01, 8.63064861e-01],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.26781186e-01, 3.75984780e-03],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00]])

## 4.1.6神奇索引
用来描述使用使用整数数组进行数据索引
注意  布尔索引与切片不同，它总会将数据复制到一个新的数组中

In [346]:
arr=np.zeros((8,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [347]:
for i in range(8):
 arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [348]:
arr[[4,3,0,6]]    #可以用一个数组来传达索引

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [349]:
arr[[-5,-6,-3]]#如果索引为负值将从尾部进行选择

array([[3., 3., 3., 3.],
       [2., 2., 2., 2.],
       [5., 5., 5., 5.]])

In [350]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [351]:
arr[[1,5,7,2],[0,3,1,2]]#根据每个索引元组选出一个一维数组

array([ 4, 23, 29, 10])

In [352]:
arr[[1,5,7,2]][:,[0,3,1,2]]#选中矩阵中行列子集组成的矩形区域

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## 4.1.7数组转置与换轴
    转置是一种特殊的数组重组形式，可以返回底层数组的视图而不需要赋值任何内容。数组拥有transpose方法，也有特殊的T属性：

In [353]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [354]:
arr.T    #转置运算

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [355]:
np.dot(arr.T,arr)   #按成两个矩阵相乘的操作

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [356]:
arr=np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [357]:
arr.transpose((1,0,2))  #对数组进行换轴运算

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

# 4.2通用函数：快速的逐元素数组函数
通用函数也称为ufunc，是一种在ndarry数据中进行逐元素操作的函数，某些函数接收一个或者多个标量数值，并产生一个或多个标量结果，而通用函数就是对这些函数的简单函数的量化封装。

## 4.2.1一元通用函数　　　　　　　　　　　　　　　　
abs、fabs <br>
sqrt、(与arr ** 0.5类似)<br>
square(与arr ** 2类似)<br>
exp
log、log10、log2、log1p(log(1+x))<br>
sign<br>
ceil　　　　　　　　　　　　　　#计算每个元素的最大整数值<br>
floor　　　　　　　　　　　　　 #计算每个元素的最小整数值<br>
rint　　　　　　　　　　　　　　#将元素保留到整数位<br>
modf<br>
isnan　　　　　　　　　　　　　#返回数组中的元素是否为一个NaN（不是一个数值），形式为布尔值数组<br>
cos、sin、cosh、sinh、tanh、arccos、arcsin<br>
logical_not(与arr效果一致)<br>

In [358]:
#很多ufunc是简单的逐元素转换，一元通用函数，比如sprt或exp函数：
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [359]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [360]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

## 4.2.2二元通用函数
add　　　　　　　　　　　　　　#将数组对应元素相加<br>
multiply
divide、floor_divide　　　　   #除或者整除（放弃余数）<br>
power　　　　　　　　　　　　　#将第二个数组中的元素作为第一个数组中的元素的幂次方<br>
maximum、fmax　　　　　　　　　#逐个元素计算最大值，fmax忽略NaN<br>
minimum、fmin　　　　　　　　　#逐个元素计算最小值，fmin忽略NaN　<br>
mod　　　　　　　　　　　　　　#按元素的求模运算（求除法的余数）<br>
greater、less、great_equal、less_equal、equal、not_equal　　　　　　#与数学操作符>、<、>=、<=、==、！=效果一致<br>
logical_and、logical_or、logical_and、logical_and、logical_xor　　　#进行逐个元素的逻辑操作<br>

In [361]:
#二元通用函数,比如add或maximum则会接收两个数组并返回一个数组作为结果。
x=np.random.randn(8)
y=np.random.randn(8)
x

array([-0.78844018,  1.52940067,  0.20545485,  0.31301313,  0.86652071,
        0.29907053,  1.07654064,  0.36317735])

In [362]:
y

array([ 1.89367983, -0.48575274,  0.38767446,  0.02355761, -0.6602295 ,
       -0.31868493, -0.72266219,  0.17738672])

In [363]:
np.maximum(x,y)#逐个元素的将x和y中元素的最大值计算出来

array([1.89367983, 1.52940067, 0.38767446, 0.31301313, 0.86652071,
       0.29907053, 1.07654064, 0.36317735])

In [364]:
a,b=np.modf(x)#返回一个浮点数组的小数部分和整数部分
b

array([-0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.])

In [365]:
np.floor(x)

array([-1.,  1.,  0.,  0.,  0.,  0.,  1.,  0.])

# 4.3使用数组面试向数组编程

In [366]:
points=np.arange(-5,5,0.01)

In [367]:
xs,ys=np.meshgrid(points,points)
print(xs)
print(ys)

[[-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 ...
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]]
[[-5.   -5.   -5.   ... -5.   -5.   -5.  ]
 [-4.99 -4.99 -4.99 ... -4.99 -4.99 -4.99]
 [-4.98 -4.98 -4.98 ... -4.98 -4.98 -4.98]
 ...
 [ 4.97  4.97  4.97 ...  4.97  4.97  4.97]
 [ 4.98  4.98  4.98 ...  4.98  4.98  4.98]
 [ 4.99  4.99  4.99 ...  4.99  4.99  4.99]]


In [368]:
z=np.sqrt(xs ** 2+ys ** 2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

## 4.3.1将条件逻辑作为数组操作
np.where的用法：
1.三元表达式x if condition else y
2.根据数组来生成一个新的数组

In [369]:
x=np.array([1.1,1.2,1.3,1.4,1.5])
y=np.array([2.1,2.2,2.3,2.4,2.5])
cond=np.array([True,False,True,False,True])
result=np.where(cond,x,y)
result

array([1.1, 2.2, 1.3, 2.4, 1.5])

In [370]:
arr=np.random.randn(4,4)
arr

array([[ 0.98351273,  0.02350459,  0.55377698,  0.35376929],
       [-0.27559363, -0.49048359, -0.3744366 , -2.39750398],
       [ 1.54102998,  0.06308454, -0.28444068, -1.26560054],
       [ 1.78797963, -0.35450871, -0.10476112,  0.38625369]])

In [371]:
arr>0

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [ True,  True, False, False],
       [ True, False, False,  True]])

In [372]:
np.where(arr>0,2,-2)#后两个参数均为标量的情况

array([[ 2,  2,  2,  2],
       [-2, -2, -2, -2],
       [ 2,  2, -2, -2],
       [ 2, -2, -2,  2]])

In [373]:
np.where(arr>2,2,arr)#标量和数组联合作为参数

array([[ 0.98351273,  0.02350459,  0.55377698,  0.35376929],
       [-0.27559363, -0.49048359, -0.3744366 , -2.39750398],
       [ 1.54102998,  0.06308454, -0.28444068, -1.26560054],
       [ 1.78797963, -0.35450871, -0.10476112,  0.38625369]])

## 数学和统计方法
基础数组统计方法：<br>
sum<br>　　　　　　　#可选参数为axis（选择轴向）
mean<br>　　　　　　　#可选参数为axis（选择轴向）
std,var 　　　　　　　#标准差和方差，可选参数为自由度n<br>
min,max<br>
argmin,argmax<br>
cunsum 　　　　　　　#从0开始元素累积和，结果为一行数组,可选参数为axis（选择轴向）<br>
cumprod 　　　　　　　#从1开始元素累积积，结果为一行数组,可选参数为axis（选择轴向）<br>

In [374]:
arr=np.random.randn(4,4)
arr

array([[ 0.82277537, -0.68378982,  1.05720333,  0.03187997],
       [ 1.34318246, -0.05053969, -0.36400996, -1.55334234],
       [-0.3192978 ,  0.52704645,  0.7111124 , -0.21754548],
       [ 2.63779121, -1.74213763, -0.09443481,  1.43118375]])

In [375]:
arr.mean()#np.mean(arr)


0.22106733881191834

In [376]:
arr.mean(axis=1)#计算每一列的平均值

array([ 0.30701721, -0.15617738,  0.17532889,  0.55810063])

In [377]:
arr.cumsum()

array([0.82277537, 0.13898555, 1.19618888, 1.22806886, 2.57125131,
       2.52071162, 2.15670167, 0.60335933, 0.28406153, 0.81110798,
       1.52222038, 1.3046749 , 3.94246611, 2.20032848, 2.10589367,
       3.53707742])

In [378]:
arr1=np.array([1, 2, 3, 4, 5, 6, 7])
arr1.cumprod()

array([   1,    2,    6,   24,  120,  720, 5040], dtype=int32)

## 布尔值数组的方法
对于

In [379]:
arr=np.random.randn(100)
bools=arr>0

In [380]:
(arr<0).sum()#根据条件先将数组转化为布尔类型，之后对满足条件的元素求和

48

In [381]:
bools.all()#检查数组中是否每个值都是true,只能对布尔类型的数组使用
#bools.any()#检查数组中是否至少有一个true，只能对布尔类型的数组使用

False

## 4.3.4排序
Numpy可以使用sort（）方法按位置排序，可选参数为轴向：axis=0（列），axis=1（行）。

In [382]:
arr=np.random.randn(5,3)
arr

array([[ 1.38864738,  1.08771374,  0.43880126],
       [-0.96160224,  1.24560994,  0.50292552],
       [-0.63139878, -0.70425205, -0.24048254],
       [ 0.58559931,  0.35280056, -1.81555769],
       [-0.91012385, -0.74852795, -0.10812493]])

In [383]:
arr.sort(axis=1)
arr

array([[ 0.43880126,  1.08771374,  1.38864738],
       [-0.96160224,  0.50292552,  1.24560994],
       [-0.70425205, -0.63139878, -0.24048254],
       [-1.81555769,  0.35280056,  0.58559931],
       [-0.91012385, -0.74852795, -0.10812493]])

## 唯一值与其他集合逻辑
Numpy中包含一些针对一维naarry的基础集合操作。常用的方法之一是np.unique，返回的是数组中唯一值排序后形成的数组。
数组的集合操作：
unique(x)　　　　　　#计算x的唯一值并排序
intersect1d(x,y)　　　#计算x和y的交集，并排序
union1d(x,y)　　　　　　#计算x和y的并集并排序
setdiff1d(x,y)　　　　　#差集，在x中但不在y中的x的元素

In [384]:
names=np.array(['Bob','Joe','Will','Bob','Joe','Will'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [385]:
x=np.array([4,6,5,6,2,3,4])
y=np.array([1,7,5,6,6,3,4])
np.intersect1d(x,y)#计算x和y的交集，并排序

array([3, 4, 5, 6])

# 4.4使用数组进行文件输入和输出
numpy可以在硬盘中将数据以文本或二进制文件的形式进行存入硬盘或有硬盘载入。当然大部分用户还是倾向使用pandas来载入文本或者表格型数据。np.save和np.load是高效存取硬盘数据的两大工具函数。
np.load('文件名'，arr)

# 4.5线性代数
线性代数，比如矩阵乘法、分解、行列式等方阵数学是所有数组类库的重要组成部分。<br>
常用的线性代数函数列表：<br>
diag 　　　　　　　  #将方阵的对角元素作为一维数组返回，或者将一维数组转化成一个方阵，非对角元素为零。<br>
dot　　　　　　　　　#矩阵点乘<br>
trace　　　　　　　　#求迹<br>
以下函数需在numpy.linalg里面调用，上面三个函数可以在numpy里面直接调用<br>
det　　　　　　　　　#计算矩阵的行列式<br>
eig 　　　　　　　　 #计算方阵的特征值和特征向量<br>
inv　　　　　　　　　#计算方阵的逆矩阵<br>
qr 　　　　　　　　　#计算QR分解<br>
svd　　　　　　　　　#计算奇异值分解<br>
solve　　　　　　　　#求解线性系统Ax=b,其中A为方阵<br>

In [386]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[6,23],[-1,7],[8,9]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [387]:
x.dot(y)#矩阵点乘积
#np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [388]:
#from numpy.linalg import inv,qr
mat=x.T.dot(x)
np.linalg.svd(mat)

(array([[-0.42866713,  0.80596391,  0.40824829],
        [-0.56630692,  0.11238241, -0.81649658],
        [-0.7039467 , -0.58119908,  0.40824829]]),
 array([9.04026725e+01, 5.97327474e-01, 6.43761763e-16]),
 array([[-0.42866713, -0.56630692, -0.7039467 ],
        [ 0.80596391,  0.11238241, -0.58119908],
        [-0.40824829,  0.81649658, -0.40824829]]))

# 4.6伪随机数的生成
numpy.random模块可以高效生成多种概率分布下的完整样本值数据：<br>
numpy.random中部分函数列表：<br>
rand　　　　　　　　　　　 #从均匀分布中抽取样本<br>
randn　　　　　　　　　　　#从均值0和方差1的正态分布中抽取样本<br>
normal　　　　　　　　　　　#从正态（高斯）分布中抽取样本<br>
randint　　　　　　　　　　#根据给定的由低到高的范围抽取随机整数<br>
beta　　　　　　　　　　　　#从beta分布中抽取样本<br>
shuffle　　　　　　　　　　#随机排列一个序列,函数输入为序列<br>
seed　　　　　　　　　　　　#向随机数生成器传递随机状态种子<br>
uniform　　　　　　　　　　　#从均匀（0,1）分布中抽取样本<br>

In [392]:
a=np.random.randint(4,9,size=3)
a

array([8, 5, 7])

In [393]:
np.random.shuffle(a)
a

array([8, 7, 5])